GET http://localhost:3000/

###
GET http://localhost:3000/api/blogs

###
GET http://localhost:3000/api/blogs/4

###
POST http://localhost:3000/api/blogs
Content-Type: application/json

{
    "author" : "utku",
    "url" : "utku.com",
    "title": "utkucuğum"
}
###
PUT http://localhost:3000/api/blogs/10
Content-Type: application/json

{
    "author" : "utku",
    "url" : "utku.com",
    "title": "utkucuğum"
}

###
DELETE http://localhost:3000/api/blogs/11
