GET http://localhost:3000/

###
GET http://localhost:3000/api/blogs

###
GET http://localhost:3000/api/blogs/12

###
POST http://localhost:3000/api/blogs
Content-Type: application/json

{
    "author" : "utku",
    "url" : "utku.com",
    "title": "utkucuğum"
}
###
PUT http://localhost:3000/api/blogs/12
Content-Type: application/json

{
    "author" : "utkumal2",
    "likes" : 2
}

###
DELETE http://localhost:3000/api/blogs/11
