GET http://localhost:3000/

###
GET http://localhost:3000/api/blogs?search=react

###
GET http://localhost:3000/api/blogs/16

###
POST http://localhost:3000/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InV0a3VjYW5AZm9vLmNvbSIsImlkIjoyLCJpYXQiOjE2NzA5NjYyNzN9.wTSD31IonN0jwqBt5uCtSUsyy8PbBpGmr2GSQ1YQ8DY

{
    "author" : "utkucan post1 relational",
    "url" : "utku.com",
    "title": "react"
}
###
PUT http://localhost:3000/api/blogs/12
Content-Type: application/json

{
    "author" : "utkumal2",
    "likes" : 2
}

###
DELETE http://localhost:3000/api/blogs/15
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InV0a3VjYW5AZm9vLmNvbSIsImlkIjoyLCJpYXQiOjE2NzA5NjYyNzN9.wTSD31IonN0jwqBt5uCtSUsyy8PbBpGmr2GSQ1YQ8DY

